{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "gzac-backend.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if and .Values.ingress.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.ingressClassName}}
  {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gzac-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}

  {{- if or .Values.ingress.hosts .Values.ingress.host }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /api
          {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: Prefix
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
            {{- else }}
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
            {{- end }}
        - path: /v3
          {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: Prefix
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
            {{- else }}
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
            {{- end}}
        - path: /operaton
          {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: Prefix
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
            {{- else }}
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
            {{- end }}
      {{- end }}
    {{- end }}
{{- end }}